### ISSUE TITLE
whichkey.show command doesn't work when used from VSCodeVim keybinding

### ISSUE THREAD

**Issue by roblabla** [VSpaceCode/vscode-which-key#1]
I'm using vscode-which-key standalone (without VSpaceCode). I have the following VSCodeVim keybinding set up to bring the which-key menu:

```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>"],
            "commands": ["whichkey.show"]
        },
      ]
```

When I run the keybinding, I get an empty quick-pick menu:
![image](https://user-images.githubusercontent.com/1069318/86159896-4aab5c00-bb0b-11ea-8c16-1b1a4c124dfe.png)

However, if I open the VSCode Command Palette and run the `whichkey.show` action from there, the command seems to run properly:
![image](https://user-images.githubusercontent.com/1069318/86159832-32d3d800-bb0b-11ea-8c17-660f7ae3945e.png)

**Comment by stevenguh** [comment]
Ah. The way VSCode execute command is with an empty args array by default instead not passing arguments in the case of vscode command palette. I will fix that this afternoon.

**Comment by stevenguh** [comment]
Released the fix. Give it a few minutes for Microsoft to process.
