### ISSUE TITLE
`whichkey.sortOrder` - sort alphabetically with characters before numbers?

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/vscode-which-key#10]
Sorry I know I'm getting picky about this now, but it'd be wonderful if you could sort by characters first and then by numbers (special characters I don't particularly care about, they can stay where they are). Right now when hitting `<space>` with VSpaceCode, half of the menu items that show up are just selections for focusing a particular editor group; which is definitely handy, but I'd argue is not an action I'll need to reference very often.

**Comment by stevenguh** [comment]
The option was designed to supported more than one sorting option. I kind of expected this will happen.
This is sorting non-number first looks like. Does that work for you?
![screenshot](https://user-images.githubusercontent.com/3455662/89208211-c9fbd780-d570-11ea-9b9f-f68c63f35367.png)

**Comment by macintacos** [comment]
Yes that'd be perfect!

**Comment by stevenguh** [comment]
Added that option in b1250585cf34c5ff57c6f02e02cfa8baf29e226a and released `v0.7.6`
