### ISSUE TITLE
Unable to use it with VSCodeVim easy motion

### ISSUE THREAD

**Issue by gquittet** [VSpaceCode/vscode-which-key#15]
When I press the leader key, Which Key is displayed directly.

I've tried the `delay` option but I can't use anymore the easy motion plugin of VSCodeVim with this extension.

Do you know how can I do to make it work which key and easy motion without overriding it?

**Comment by stevenguh** [comment]
This plugin is not using the leader key. What's your setup? Are you using VSpaceCode? Were you at one point using the leader key approach with VSpaceCode? See https://github.com/VSpaceCode/VSpaceCode/issues/90

**Comment by MarcoIeni** [comment]
When you report a bug you should follow the instructions of the [bug report template](https://github.com/VSpaceCode/vscode-which-key/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by danielo515** [comment]
@MarcoIeni the template is nice when you want to report a bug, but this is just a functionality that is not taken in account. I think the title and the description are descriptive enough. I'm having the same problem by the way.

**Comment by MarcoIeni** [comment]
Some of the info asked by stevenguh are part of the template, that's why I pointed it out.

**Comment by stevenguh** [comment]
The current `<spc> j` contains easy motion key bindings like `<spc> j w` to jump word for example. I need more description than what I have here to understand. Is there something new about easy motion that I don't know? Or is it some misconfiguration? like @MarcoIeni said, understanding what config you are running can help.

**Comment by danielo515** [comment]
I'm pretty sure the problem is a combination of keybindings overrides and lack of docs (both, on this repo and on VSCodeVim one).
Not sure if this plugin uses space as default to activate the which key, but VSpaceCode does.
Given that there is no documentation about how to remap keys when you run a WhichKey command/option (I know there is now an issue for that) and that the only way according to VSCodeVim docs (https://github.com/VSCodeVim/Vim#vim-easymotion) to activate easymotion is by remapping keys (there is nothing like vim.easymotionForward) I'm pretty sure that is the root cause of this problem.

**Comment by stevenguh** [comment]
> Not sure if this plugin uses space as default to activate the which key, but VSpaceCode does.

This VSpaceCode uses the space key to activate the which key if you choose the "automatic" installation. And both plug-ins allow you to customize which key you what to use to activate.

> I know there is now an issue for that

I just link it here, so people can follow
https://github.com/VSpaceCode/vspacecode.github.io/issues/3


> that the only way according to VSCodeVim docs (https://github.com/VSCodeVim/Vim#vim-easymotion) to activate easymotion is by remapping keys (there is nothing like vim.easymotionForward) I'm pretty sure that is the root cause of this problem.

As far as I know, there isn't really a way to call it directly, so we have to call it with the leader key. If a user changed its leader, the easy motion might not work right off the box. We should update the doc with that information. Feel free to help us update the doc.

In the Vim repo, the current maintainer also talked about an external API for other extension to use so we might able to call directly to Vim to activate easy motion. https://github.com/VSCodeVim/Vim/issues/5073

**Comment by stevenguh** [comment]
Documented how to use vim remap. @gquittet @danielo515 Is this still an issue?

**Comment by gquittet** [comment]
Not for me.

**Comment by danielo515** [comment]
Docs looks awesome. Yes, I think this is  not a problem anymore

**Comment by gen1321** [comment]
Just in case some one is having issue with easymotion.

Remove ` "vim.leader": " ",` from settings.json
