### ISSUE TITLE
Delay Configuration?

### ISSUE THREAD

**Issue by ChristianChiarulli** [VSpaceCode/vscode-which-key#17]
I may have missed this but is there a way to speed up the delay?

**Comment by stevenguh** [comment]
See https://vspacecode.github.io/docs/extra#display-menu-with-a-delay

**Comment by dvornikita** [comment]
Hello, 
I was wondering how exactly you did this. I put `  "whichkey.delay": 1,` in the settings.json and it does not yield any effect. The delay is still significant. I am doing something wrong?
Thank you.
