### ISSUE TITLE
Add `+` before each sub menu

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/vscode-which-key#21]
I am opening this after discussion on https://github.com/VSpaceCode/VSpaceCode/issues/130

## Problem

It is not easy to understand when a key binding is an action or it is a sub menu.
For example, right now we manually add "..." at the end of a submenu in VSpaceCode:

![image](https://user-images.githubusercontent.com/11428655/97343989-7572aa80-1888-11eb-83ba-17d928f8acd5.png)

## Solution

Which key should automatically add the `+` character in front of each binding that has a sub menu.

![image](https://user-images.githubusercontent.com/11428655/97344104-9cc97780-1888-11eb-9a96-89154ca54ce9.png)

You can add an option to which key that let users customize the `+` sign. Users can edit it, so they can have an icon, a different character or just leave it blank with `""`.

**Comment by stevenguh** [comment]
Just experiment with this a little bit with this. Having auto prefix is a little bit tricky with conditional bindings as we don't know which command (could be a command or another binding menu). We will not know until a user pressed a corresponding the key, so we cannot automatically add prefix for conditional bindings. In short term, manually replacing "..." will be the quickest way have this turn around.

**Comment by MarcoIeni** [comment]
Ok, we can close this issue and I can replace "..." with "+"

**Comment by stevenguh** [comment]
That sounds good to me. We can use this to track the work?

**Comment by MarcoIeni** [comment]
Yes, I will do it and I will close this issue.

**Comment by stevenguh** [comment]
Should we modify this repo as well for consistent?

**Comment by MarcoIeni** [comment]
Yes, we could, anyway, this repo doesn't follow spacemacs conventions, so it's up to your personal taste :)
If you want me to update it just reopen this issue and assign it to me.

**Comment by stevenguh** [comment]
It would be nice to have the consistency since the '+' is also what which-key uses. I reopened it, and thank you very much :)
