### ISSUE TITLE
Incrementally add/replace Menu Customization does not work.

### ISSUE THREAD

**Issue by gianko** [VSpaceCode/vscode-which-key#25]
## Bug description
Followed documentation step to add/replace menu items and it has no effect.

## To Reproduce

Follow documentation steps, try `<Space> g s` and it will still open the magit status.

## Expected behavior

Menu action would now be "workbench.action.gotoLine"

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
{
  "whichkey.bindingOverrides": [
    {
      "keys": "g.s",
      "name": "Go to line",
      "type": "command",
      "command":"workbench.action.gotoLine",
    }
  ]
}
```

</p>
</details>

## System information

![image](https://user-images.githubusercontent.com/1309885/102019217-f6aad180-3d50-11eb-8687-d342a073a038.png)

About VSCode
```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by stevenguh** [comment]
I saw you installed vspacecode, so I assumed you want to change the default bindings for VSpaceCode and not the `which-key` one. You will need to change `vspacecode.bindingOverrides` instead.

**Comment by MarcoIeni** [comment]
Also, if you are using VSpaceCode, you should follow https://vspacecode.github.io/docs/#manual-configuration-optional since I noticed your `settings.json` file doesn't have stuff like:

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<space>"
            ],
            "commands": [
                "vspacecode.space"
            ]
        }
    ],
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<space>"
            ],
            "commands": [
                "vspacecode.space"
            ]
        }
    ],
```

**Comment by MarcoIeni** [comment]
Since one month has passed I am closing this. Feel free to comment if you need additional support if you don't find what you need in our [docs](https://vspacecode.github.io/docs/)
