### ISSUE TITLE
How to add easymotion keybindings

### ISSUE THREAD

**Issue by milosavljevicoa** [VSpaceCode/vscode-which-key#29]
I want to create my custom whichkey "menu" and I have been struggling to add easymotion. As with VSpaceCode when i press `<space>-j` then i get a list of possible jump points, `<space>-j-w` does easymotion jump start of word. I want do add same behavior in my whichkey.bindings but with no luck.

here is an example that i have tried
```
"whichkey.bindings": [
      ...
     {
            "key": "e",
            "name": "Easymotion",
            "type": "bindings",
            "bindings": [
                {
                    "key": "w",
                    "name": "jump word",
                    "type": "command",
                    "args": ["leader", "leader", "leader", "b", "d", "w"] 
                },
                 ....
            ]
      },
       ...
]

```

Which key stops working after adding this and i get this error 
![image](https://user-images.githubusercontent.com/47518781/112730954-bd2f5800-8f34-11eb-8410-70dbcd00905f.png)
I know i am doing something wrong but i don't know what.

**Comment by stevenguh** [comment]
You can see how easymontion is implemented on VSpaceCode. You are missing the command and had the incorrect args.
https://github.com/VSpaceCode/VSpaceCode/blob/v0.9.1/package.json#L1182-L1194

Are you using whichkey standalone or VSpaceCode? Do you want to create all bindings from starch?
`whichkey.bindings` is for when you want to create all the bindings from scratch with which-key running standalone.

If you just want to modify a section of the bindings, overrides are good option, See https://vspacecode.github.io/docs/whichkey/#menu-customization

If you are using VSpaceCode, see https://vspacecode.github.io/docs/menu-customization#incrementally
