### ISSUE TITLE
Selection can be hard to see in some themes

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/vscode-which-key#3]
> By the way just a suggestion, but if you want the selection to look better (currently in some themes the inactive selection is barely noticeable) you can try to change the setting "editor.inactiveSelectionBackground" from "workbench.colorCustomizations" to ThemeColor('editor.selectionBackground') when opening the QuickPick menu and then change it back to whatever the user had it set or undefined if it wasn't set when closing the QuickPick menu. I haven't tested this but it should work.

_Originally posted by @berknam in https://github.com/VSCodeVim/Vim/pull/5050#issuecomment-665564308_

**Comment by stevenguh** [comment]
This approach doesn't quite work as `ThemeColor` is only a reference and cannot get the actual color of `editor.selectionBackground`

**Comment by berknam** [comment]
Yeah you're right. Didn't think about that. The `ThemeColor` would only work if using a text editor decoration, which might be a possibility but I don't know if that would work well.

I guess the easier option is to add a warning to the readme file telling the user to change that setting when they can't see the inactive selection:
```json
"workbench.colorCustomizations": {
    "editor.inactiveSelectionBackground": "some color that looks better",
},
```

**Comment by stevenguh** [comment]
I added that to readme, and close this issue for now. We can revisit this if there's a better solution.
