### ISSUE TITLE
KeyDetection happening on wrong workspaces

### ISSUE THREAD

**Issue by Enzodtz** [VSpaceCode/vscode-which-key#33]
## Bug description

To open the menu, by default you have to press `space`. The problem is that when you're in somewhere such as `Ctrl+F` (Find) or even in some of the vscode menu screens (for example extensions one), pressing space will trigger the menu, and it will prevent you from searching for example.

## To Reproduce

1. Go to any vscode screen different than the file editor
2. Press `space` (or the key for open the menu)
3. The menu will open

## Expected behavior

Open the menu just if focusing the text editor.

## Aditional context

I could achieve this functionality by changing the default keybindings.json that I had before, which was:

```json 
{
    "key": "space",
    "command": "whichkey.show",
    "when": "neovim.mode != 'insert'"
}
```

to:

```json
{
    "key": "space",
    "command": "whichkey.show",
    "when": "editorTextFocus && neovim.mode != 'insert'"
 }
```

Since I don't really work on vscode extensions, I could not find where to put this into the source code to open a pull request, but I think it should be easy.

Thanks.

**Comment by stevenguh** [comment]
From your additional context, I think this is a documentation issue for neovim with standalone which-key.

In VSpaceCode, we use the following keybindings to trigger the menu for when the editor is out focus:
https://github.com/VSpaceCode/VSpaceCode/blob/v0.9.1/src/configuration/keybindings.jsonc#L2-L13

Combining with this comment https://github.com/VSpaceCode/VSpaceCode/issues/34#issuecomment-673235610 to trigger which-key within neovim, you issue should be resolved.

If that works well for you, we would love to get some help to improve the documentation at https://github.com/VSpaceCode/vspacecode.github.io/blob/master/docs/whichkey/usage.md.

**Comment by Enzodtz** [comment]
Sorry, I think that this was a misunderstood by me. Thank you anyway
