### ISSUE TITLE
Race condition when chaining keys too quickly

### ISSUE THREAD

**Issue by The-Compiler** [VSpaceCode/vscode-which-key#39]
If I hit `SPC p f` quickly, I can see `pf` being entered into the first QuickPick (before the second one gets displayed), then I end up in the `+Project` menu rather than the `+Find file in project` one.

edit: I can see there's some handling for this kind of case here:

https://github.com/VSpaceCode/vscode-which-key/blob/9c6ad3ab8ed229a5f40a23d2bb7b2af330bf7edf/src/menu/menu.ts#L107-L125

and indeed it gets much better when I set `whichkey.delay` to `1` instead of `0`. Maybe that logic should be active in some way even without a delay. I can try contributing a fix, but it might take me a while as I have a lot on my plate with my own projects :slightly_smiling_face:

_Originally posted by @The-Compiler in https://github.com/VSpaceCode/vscode-which-key/issues/38#issuecomment-843919654_

**Comment by The-Compiler** [comment]
Reply by @stevenguh over in #38:

> For this case, it can be adjacent to original issue. **But let's open another issue to track it**. I think the cause of this is probably because multiple `onDidChangeValue` events are called before the pervious one has a chance to complete, and the time to finish `onDidChangeValue` probably also increased by #34. Two attempts in my heads are
> 
> 1. Have a queue to batch the `onDidChangeValue` to handle event in sequence. However, probably won't work by itself for the upcoming 1.57 (#34) due to how we modify the input.
> 2. Change the input handling completely to eliminate modification of the input field.
> 
> > indeed it gets much better when I set whichkey.delay to 1 instead of 0. Maybe that logic should be active in some way even without a delay
> 
> The difference is that
> 
> https://github.com/VSpaceCode/vscode-which-key/blob/9c6ad3ab8ed229a5f40a23d2bb7b2af330bf7edf/src/menu/menu.ts#L239-L245
> 
> is running on asynchronously when delay is 1. The might be due to us needing to have a workaround to await for set value for #34.
> @The-Compiler Wondering what's the version of vscode you are running? Can you also try which-key version v0.8.4 to see if it's any better? Btw, I am also having trouble reproducing the issue on my computer

**Comment by The-Compiler** [comment]
I'm on VS Code 1.56.2 on Archlinux:

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.12.3-arch1-1

What's the easiest way I can try the older version? I'm trying to get a development setup, but no dice so far - I'll open a separate issue for that, though chances are that's a problem on my side of some sorts.

**Comment by stevenguh** [comment]
> What's the easiest way I can try the older version? I'm trying to get a development setup, but no dice so far - I'll open a separate issue for that, though chances are that's a problem on my side of some sorts.

You can choose to `Install Another Version` from the extension page of VSCode.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/3455662/119069863-c4ef0400-b99b-11eb-8f63-222607c57025.png">

**Comment by The-Compiler** [comment]
Sorry for the looong delay, I kinda lost track of this one (but it still trips me up from time to time :sweat_smile:).

Indeed v0.8.4 works fine, and a git bisect tells me that 32125626900d08d17e0cfacf61d34f8f75535a0f ("Fix the onDidChangeValue API change of QuickPick") introduced the issue.

If you're on Linux, the easiest way to reproduce this is `sleep 2 && xdotool type  ' pf'` and then focusing the VS Code window. In about 3 out of 4 cases, this will result in being in the "Project" menu, rather than the file menu.

**Comment by stevenguh** [comment]
> Indeed v0.8.4 works fine, and a git bisect tells me that 32125626900d08d17e0cfacf61d34f8f75535a0f ("Fix the onDidChangeValue API change of QuickPick") introduced the issue.

Thanks for tracking it down 😄 I suspect that would be that case since that commit introduced a lot more awaits in order get around vscode API change while keeping existing model. vscode api 🤦🏻‍♂️

> 1. Have a queue to batch the `onDidChangeValue` to handle event in sequence. However, probably won't work by itself for the upcoming 1.57 (#34) due to how we modify the input.
> 2. Change the input handling completely to eliminate modification of the input field.

Those two options I mentioned are still applicable, but I'd like to push the new version out first then come back to this.

> If you're on Linux, the easiest way to reproduce this is sleep 2 && xdotool type ' pf' and then focusing the VS Code window. In about 3 out of 4 cases, this will result in being in the "Project" menu, rather than the file menu.

I don't have a native linux, I probably will setup a VM for it when I get to this.

**Comment by The-Compiler** [comment]
What OS are you on? I do have access to Windows and macOS 10.14, so I can find a similar reproducer there most likely.

**Comment by stevenguh** [comment]
I have access to macOS and Windows. It will speed things up if you can find a way to reproduce on one of those platforms :)

**Comment by The-Compiler** [comment]
Hah, while trying to find a reproducer there, I just discovered that the issue actually vanished after upgrading to VS Code 1.57.0 :tada: 

If you were using the Insiders Build that might've been the reason why you couldn't reproduce it! If you still want to track this down, [download the older VS Code](https://code.visualstudio.com/updates/v1_56) and:

# Windows

- Install [Autohotkey](https://www.autohotkey.com/)
- Save this as `pf.ahk`:

```
^j::
Send, {Space}
Sleep, 100
Send, pf
return
```

- Double click it
- Press Ctrl-j in VS Code.

# macOS

- Run `sleep 2 && osascript -e 'tell application "System Events" to keystroke space' -e 'tell application "System Events" to keystroke "pf"'`
- Grant permissions
- Run again
- Switch to VS Code

---

But probably not worth the trouble, given that this is a corner case which doesn't appear with the newest VS Code version now. So if you prefer, feel free to close! :sweat_smile:

**Comment by stevenguh** [comment]
If it doesn't appear in the latest version, let's close this one. We can reopen it if it appears again and spend some time attempting to fix it on our side.

**Comment by The-Compiler** [comment]
Agreed, thanks!
