### ISSUE TITLE
Trouble getting development set up

### ISSUE THREAD

**Issue by The-Compiler** [VSpaceCode/vscode-which-key#40]
Taking the freedom to open an issue for this, as I'm pretty stuck and hope someone here can help me out. I'm trying to wrap my head around extension development so I can maybe contribute a few small fixes in the future (when I find the time, that is...).

According to https://github.com/VSpaceCode/vscode-which-key/blob/master/CONTRIBUTING.md I should be able to use "Run Extension" from VS Code, and get a new window with the extension installed. I can see the extension getting built, and a new "[Extension Development Host]" instance of VS Code gets started.

However, it looks like that new instance still has my normal extension setup, and my changes aren't getting reflected there. For example, I tried to change `+Debug` to `+Debug test` in `package.json`, but the menu in the new window still shows `+Debug`.

Am I missing something here? I have no experience at all with npm/webpack/Typescript/VS Code extensions (I'm mainly doing Python), so maybe there's something obvious I'm not aware of?

**Comment by stevenguh** [comment]
The new window should be running with the new which-key extension. I assume you modified which-key's `package.json`, and trigger QuickPick menu with the VSpaceCode's config?

The way this works is that VSpaceCode and which-key both have their own default binding config in `package.json`. When you launch another instance from "Run Extension" in the which-key repo, it installed new `which-key` extension in the new debug instance. When you trigger `SPC` in that debug instance it may still using `VSpaceCode` binding depending on your setting.

If you want to test which-key's default bindings in the `package.json`, I usually do `SPC SPC` and type `which key` and click `Which Key: Show Menu` in the new debug vscode instance.

**Comment by The-Compiler** [comment]
> The way this works is that VSpaceCode and which-key both have their own default binding config in `package.json`. When you launch another instance from "Run Extension" in the which-key repo, it installed new `which-key` extension in the new debug instance. When you trigger `SPC` in that debug instance it may still using `VSpaceCode` binding depending on your setting.

Ah, right, that was precisely the issue! I was wondering where the bindings lived, so I searched and found the ones in `which-key`, but I was actually looking at the `VSpaceCode` menu. I wonder if it really makes sense to maintain them at both places, though?

**Comment by stevenguh** [comment]
It was an early design choice. The which-key maintains its own bindings that doesn't require any third party extension including vim, and VSpaceCode maintains its own one that has good out-of-box keybindings similar to spacemacs.

Maintaining a full bindings at both places allows us to see the bindings explicitly in the `package.json` and allows us to execute different bindings (like one binds to `SPC`, and another one binds to `ESC`); implementing layer https://github.com/VSpaceCode/VSpaceCode/issues/199 might changed this thinking.

**Comment by MarcoIeni** [comment]
> The new window should be running with the new which-key extension. I assume you modified which-key's `package.json`, and trigger QuickPick menu with the VSpaceCode's config?
> 
> The way this works is that VSpaceCode and which-key both have their own default binding config in `package.json`. When you launch another instance from "Run Extension" in the which-key repo, it installed new `which-key` extension in the new debug instance. When you trigger `SPC` in that debug instance it may still using `VSpaceCode` binding depending on your setting.
> 
> If you want to test which-key's default bindings in the `package.json`, I usually do `SPC SPC` and type `which key` and click `Which Key: Show Menu` in the new debug vscode instance.

This was really useful also for me. Should we add it to the `CONTRIBUTING.md`?
