### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by The-Compiler** [VSpaceCode/vscode-which-key#41]
I like to have icons in menus, as it makes it easier to visually scan them. Looking at the [available icons](https://code.visualstudio.com/api/references/icons-in-labels) I wondered if I could find suitable icons for all the menu items, and indeed found something nice for almost all menus:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/625793/119241540-7d14dc00-bb57-11eb-9f19-39ddb241d89b.png)

![image](https://user-images.githubusercontent.com/625793/119241547-856d1700-bb57-11eb-851b-8e7bbc607cbf.png)

![image](https://user-images.githubusercontent.com/625793/119241552-90c04280-bb57-11eb-9ea1-c275e77a8b84.png)

![image](https://user-images.githubusercontent.com/625793/119241557-987fe700-bb57-11eb-8097-1ea6a20edc4c.png)

![image](https://user-images.githubusercontent.com/625793/119241560-a897c680-bb57-11eb-8416-8fcc289405c7.png)

</details>

Right now I just [hard-coded them into the config](https://github.com/VSpaceCode/VSpaceCode/compare/master...The-Compiler:icons), but next I'd like to add proper support. I'd propose having an `"icon"` key for a binding, which `which-key` then would display depending on a global `whichkey.showIcons` setting or so. 

How does that sound?

**Comment by stevenguh** [comment]
That's pretty cool. I implemented the support at https://github.com/VSpaceCode/vscode-which-key/commit/f5be86d4dbad195427c28d0c0007fed324b8d6b3 in the [`refactoring`](https://github.com/VSpaceCode/vscode-which-key/tree/refactoring) branch. You can switch to the branch to try it out.

It would be great if you can help us add the icons in `VSpaceCode` bindings once a new version is released.

**Comment by The-Compiler** [comment]
Awesome, thank you! FWIW I wanted to try installing the extension on the `refactoring` branch with `vsce package`, but that complains:

```
 ERROR  @types/vscode ^1.54.0 greater than engines.vscode ^1.45.0. Consider upgrade engines.vscode or use an older @types/vscode version
```

**Comment by stevenguh** [comment]
I updated some packages in that branch. Apparently, I also made the vscode type out of sync. Fixed in 1bc6ad7786d7941992e249281fffcc34aed5ae14

**Comment by The-Compiler** [comment]
Yay, thanks! I [adapted](https://github.com/The-Compiler/VSpaceCode/commit/0cc4cfe934d42304f58f0aaedcec0c2051b4308c) my changes ([regexes ftw](https://regex101.com/r/BtC2ZB/1), [see also](https://xkcd.com/208/)). Seems to work great so far. I'll wait until the next vscode-which-key release (and perhaps improve the icons a bit more until then) and then open a PR.

**Comment by stevenguh** [comment]
regexes ftw indeed. That awesome, I am finishing up documentation for the new version. Hopefully, I can release it soon especially it has been in the works for a while.

**Comment by The-Compiler** [comment]
After testing this for a bit, I noticed a couple of icons don't seem to show up:

![image](https://user-images.githubusercontent.com/625793/121096392-6971a280-c7f2-11eb-85e1-fbc2339f4d75.png)

![image](https://user-images.githubusercontent.com/625793/121096403-7098b080-c7f2-11eb-83bf-a2737065cb4a.png)

![image](https://user-images.githubusercontent.com/625793/121096437-81e1bd00-c7f2-11eb-8bfa-7722795911e1.png)

`+Window`:

![image](https://user-images.githubusercontent.com/625793/121096494-98881400-c7f2-11eb-8733-38b9802f2557.png)

`+Text`:

![image](https://user-images.githubusercontent.com/625793/121096526-a9388a00-c7f2-11eb-94f3-8f84eb7c0d98.png)

`+Zoom / *`:

![image](https://user-images.githubusercontent.com/625793/121096550-b35a8880-c7f2-11eb-810a-deb666f05576.png)

But they are defined in my `icons` branch, e.g.:

https://github.com/The-Compiler/VSpaceCode/blob/0cc4cfe934d42304f58f0aaedcec0c2051b4308c/package.json#L280

and my VS Code seems to know about them, as they get displayed when I enter `:$(selection)` (abusing https://github.com/VSCodeVim/Vim/issues/6655).

Any idea what's going wrong there?

**Comment by stevenguh** [comment]
Thanks for reporting, there are two things happening:

1. Icon in transient menu hasn't been implemented
2. The transient type will be deprecated, and are converted to a separate command internally. The conversion didn't take into account of icon key.

I will implement them before I release the new version of which-key, but I am a little busy atm. Might take a bit more time.

**Comment by The-Compiler** [comment]
No worries, take your time! :+1:

**Comment by MarcoIeni** [comment]
You could also release now and you specify in the README that icons do not work for transient mode, it's up to you :)

**Comment by The-Compiler** [comment]
FWIW while y'all don't owe me anything, I'd really appreciate if this was working before the release. I've spent a lot of time [picking >600 icons](https://github.com/VSpaceCode/VSpaceCode/compare/master...The-Compiler:icons) for all the VSpaceCode menus, and having icons for some items but not others in the same menu looks quite weird IMHO (and makes it harder to scan the contents visually with the text "jumping" around, kind of defeating the whole motivation behind those icons).

**Comment by stevenguh** [comment]
@The-Compiler, the branch is updated with icon support for transient. It would be great if you can try it out :)

**Comment by The-Compiler** [comment]
Looks great now, thank you! :rocket:

**Comment by stevenguh** [comment]
`v0.9.0` is finally released!! Closed.

@The-Compiler It would be amazing if you can open a pull request for the icon your used for the vspacecode's bindings :)

**Comment by The-Compiler** [comment]
Will open a PR later today or tomorrow! Just going through them again, as I think there are better options for some of those (e.g. I was mixing up windows and frames :sweat_smile:)
