### ISSUE TITLE
space is only to call which-key, it doesn't work other way

### ISSUE THREAD

**Issue by ChaoXu1997** [VSpaceCode/vscode-which-key#44]
space is only to call which-key, it doesn't work another way, such as I want to type a space in the terminal, but always call which-key

**Comment by stevenguh** [comment]
How did you setup you shortcuts to call whichkey.show? Are you using vscode vim?

**Comment by ChaoXu1997** [comment]
I use neovim in vscode, as follow is my shortcuts of neovim and whichkey
![image](https://user-images.githubusercontent.com/72029457/121649772-7a106a00-cacb-11eb-8ce5-577d342b3d41.png)

![image](https://user-images.githubusercontent.com/72029457/121650056-c065c900-cacb-11eb-8f8a-492c17edbba4.png)

**Comment by ChaoXu1997** [comment]
How can  I change the leader from "space" to ";"

**Comment by stevenguh** [comment]
I am not sure about neovim as I personally don't use it. Sorry can't be more helpful, but here are some threads in past that talk about it:
https://github.com/VSpaceCode/VSpaceCode/issues/34#issuecomment-673235610
https://github.com/VSpaceCode/VSpaceCode/issues/126

> space is only to call which-key, it doesn't work another way, such as I want to type a space in the terminal, but always call which-key

You might want to check your vscode shortcuts to make sure there isn't a global <space> shortcut that calls `whichkey.show`.


> How can I change the leader from "space" to ";"

I am not sure I understand. Do you mean the leader key for vim or the activation key for whichkey?

**Comment by MarcoIeni** [comment]
Closed for inactivity from reporter.
