### ISSUE TITLE
Support for VSCode Web

### ISSUE THREAD

**Issue by rstacruz** [VSpaceCode/vscode-which-key#52]
Thank you so much for this extension! I use it everyday and all my shortcuts are stored conveniently in my which-key config. Recently I tried installing it in GitHub Codespaces, and thought it might be nice to have which-key support there too.

## Problem

When trying to install this extension on something like GitHub Codespaces (https://github.dev), this error appears:

![image](https://user-images.githubusercontent.com/74385/133167549-bdd88c2e-089e-4fec-b76d-3387be8de7f5.png)

## Solution

I'm not sure why this happens, but my guess is the package needs a `"browser"` entrypoint in addition to `"main"` in package.json.

**Comment by stevenguh** [comment]
Interestingly, VSpaceCode and WhichKey can works in Codespaces when it has a container attached to it (has terminal access); however, it doesn't work when it is the [browser only editor](https://code.visualstudio.com/docs/remote/codespaces#_browserbased-editor) like github.dev.

The learn more link from the screenshot will take me to https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser.

After some digging, your are right that we will need additional entry point `"browser"` as outlined in the [Web Extensions](https://code.visualstudio.com/api/extension-guides/web-extensions) guide. I will look into it a little bit more later this week.

**Comment by stevenguh** [comment]
Fixed on 3eb1d5e4379e0ac0e98f59e38fc1280019b7864c, and released with v0.9.3.

Opened a tracker https://github.com/VSpaceCode/VSpaceCode/issues/230 for VSpaceCode as well.

**Comment by rstacruz** [comment]
This is fantastic - thank you so much!
