### ISSUE TITLE
Navigate up / back in the menu structure

### ISSUE THREAD

**Issue by tshort** [VSpaceCode/vscode-which-key#54]
Is there a key stroke to navigate to the prior menu (up / back)?

Is there a way to define a key to do that?

**Comment by stevenguh** [comment]
Currently, we don't have a way to do this. But this shouldn't be too hard to add.

**Comment by stevenguh** [comment]
Added 06fdf5718a389b1b35f92b900001fcebaf1038f4. Closing this, as it will be released in the next version.

Once the next version is released, you can use the command as a shortcut like
```
{
	"key": "ctrl+u",
	"command": "whichkey.undoKey",
	"when": "whichkeyVisible"
}
```
