### ISSUE TITLE
Show key bindings in menus

### ISSUE THREAD

**Issue by tshort** [VSpaceCode/vscode-which-key#55]
## Problem

I like how the normal VS Code command menu shows key bindings on the right side of the quick-pick menu. It's a useful way to learn keyboard shortcuts.

## Solution

Could which-key optionally do the same?

**Comment by stevenguh** [comment]
Sorry for the late reply. It is unlikely to be implemented atm.

1. There isn't really a API from vscode we can use to read all shortcuts
2. Shortcuts have context (`when`) associated to them.

The best we can do is probably
1. Put it as parenthesis next the name of the binding like the follow
```
{
	"key": "J",
	"name": "Move lines down (Ctrl + x)",
	"command": "editor.action.moveLinesDownAction",
}
```
2. Have another property in the binding object like the following (but it won't account for user modified shortcuts)
```
{
	"key": "J",
	"name": "Move lines down",
	"command": "editor.action.moveLinesDownAction",
        "shortcuts": {
                "win": "Ctrl+x",
                "mac": "Cmd+x"
        }
}
```

**Comment by tshort** [comment]
Thanks for looking! It's probably best not to do anything. I'd rather not see key bindings that might be wrong.

**Comment by stevenguh** [comment]
Closing this as I don't think realistically vscode will have API allowing extensions to read shortcuts.
