### ISSUE TITLE
[bug/ feature?]: whichkey.searchBindings should support fuzzy search

### ISSUE THREAD

**Issue by alexn-s** [VSpaceCode/vscode-which-key#70]
first of all: i love your extension and appreciate your work. thank you 💖

i noticed that the command `whichkey.searchBindings` does not support fuzzy search.
it would be great if it would. i dont know if it is by design or a bug.

vscode: 
```
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```

which key: `0.11.3`

**Comment by stevenguh** [comment]
What kind of fuzzy search are you looking for? We don't really have control over the search as it is the UI component provided by vscode.

**Comment by stevenguh** [comment]
Closing this as I am not sure what's the ask is. Feel free to reopen.
