### ISSUE TITLE
[Help Wanted] Show the menu when press g

### ISSUE THREAD

**Issue by yejianfengblue** [VSpaceCode/vscode-which-key#71]
When I press `<SPC>` key, vscode shows the menu of space key sequence.

![image](https://user-images.githubusercontent.com/28599139/196076070-52c50c0e-fa49-4e04-9abe-ba5e03bb8dd4.png)

similar to the spacemacs behavior

![image](https://user-images.githubusercontent.com/28599139/196075707-0304e5e1-5594-4289-a506-489406d6e399.png)

When I press `g` key, spacemacs shows the menu of `g` key sequence such as `gd` for `jump-to-definition` and `g;` for `evil-goto-last-change`. It's `g` key sequence, not `<SPC> g` key sequence.

![image](https://user-images.githubusercontent.com/28599139/196077013-2b394dff-876d-4108-ab7b-fd54dc59d1af.png)

When I press `g` key, vscode just shows a `g` in the status bar. I want vscode to show a menu of the `g` key sequence. Is that possible?

![image](https://user-images.githubusercontent.com/28599139/196076408-b7905c23-594e-460c-a689-6f272e3ad98e.png)

**Comment by stevenguh** [comment]
Follow https://vspacecode.github.io/docs/whichkey/#standalone and replace the space key with <kbd>g</kbd>. Let me know if you encounter any issues

**Comment by yejianfengblue** [comment]
@stevenguh Sorry for I didn't clearly describe my question before. The original question is updated.

**Comment by MarcoIeni** [comment]
oh, I see now!
At the moment this is not possible.
The keys under `<SPC>` are defined by VSpaceCode or WhichKey.
Instead, the keys under `g` are defined by you or by https://github.com/VSCodeVim/Vim
That's why it is not possible.
