### ISSUE TITLE
Support several menus

### ISSUE THREAD

**Issue by matklad** [VSpaceCode/vscode-which-key#73]
## Problem

I want to reduce the length of composite key combinations and, for that reason, I want to have several "entry points" to which keys. For example, I want `Alt+s` to pop open "symbol" menu, `Alt+f` -- "file" menu, `Alt+e` -- "edit" menu, etc. At the moment, this is not possible, as which keys defines a singleton global menu. 

## Solution

I think a nice solution would be to add an argument to `whichkey.show` to narrow the menu. I'd love to be able to have something like this in my keybindings.json

```json
    {
      "key": "alt+s",
      "command": "whichkey.show",
      "args": {"narrow": ["s"]}
    },
    {
      "key": "alt+f",
      "command": "whichkey.show",
      "args": {"narrow": ["f"]}
    },
    {
      "key": "alt+e",
      "command": "whichkey.show",
      "args": {"narrow": ["e"]}
    },
```

## Alternatives

I _think_ I can achieve this by writing my own extension which uses whichkey. `commands.executeCommand("whichkey.show", "myExtension.bindings");` + `whichkey.register` should do the trick. However, I don't think that's possible to do without an extra extension, using only user's config. 

I also tried to do this using macros extension:

```
    "macros": {
        "which.symbols": [
            "whichkey.show",
            {"command": "type", "args": {"text": "s"}}
        ],
    }
```

Sadly, the `s` is typed into the text editor, rather than into whichkey menu. 

## Additional context

Thank you for building a lovely extension :heart: !

**Comment by matklad** [comment]
I guess a third alternative is to add some sort of a lazy loading logic over here: 

https://github.com/VSpaceCode/vscode-which-key/blob/1ba0b287d1ff627c281739800d624eb4d7349b0c/src/whichKeyRegistry.ts#L50-L52

so that calling `whichkey.register` isn't needed. That way, I think I can handle this without extension?

**Comment by stevenguh** [comment]
As a workaround you can try using [ryuta46.multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command).
```
{
    "key": "alt+s",
    "command": "extension.multiCommand.execute",
    "args": { 
        "sequence": [
            "whichkey.show",
            { "command": "whichkey.triggerKey", "args": "m" },
        ]
    }
}
```

This is similar to how we did this in VSpaceCode https://github.com/VSpaceCode/VSpaceCode/blob/master/src/configuration/settings.jsonc#L33-L38

---

Maybe we should have a proper support for this... but can you try using the workaround and see if that works for you.

**Comment by matklad** [comment]
Not at the PC, but I am pretty sure that that’ll work just fine for my use-case! So probably the best fix here is to mention this trick in the docs!
