### ISSUE TITLE
Configure context menu delay?

### ISSUE THREAD

**Issue by JoshTRN** [VSpaceCode/vscode-which-key#89]
I did some brief googling and I don't think this is configurable as of right now, but what I'd like is for the which key context menu to have a brief delay before opening just like the default spacemacs configuration for example. I checked the documentation for vscode-which-key and didn't find any configuration settings in this regard. I also checked the vscode documentation and didn't find any configurability there either. Maybe it's not possible just yet, but it would be nice to not have this thing flashing every time I enter a key chord.

**Comment by MarcoIeni** [comment]
https://vspacecode.github.io/docs/whichkey/extra#display-menu-with-a-delay ?

**Comment by stevenguh** [comment]
Closing this as the delay settings seems to have addressed this. Thanks Marco for answering.
