### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Belphegor27** [VSpaceCode/vscode-which-key#91]
## Bug description

I want to use "workbench.action.terminal.sendSequence" to pass "dotnet run" for C#
But it doesn't work, while I use keybindings.json and it works

I hope I can fully get into which key to not using keybinding

## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
{
        "key": "alt+a",
        "command": "workbench.action.terminal.sendSequence",
        "args":
        {
            "text": "dotnet run"
        }
}
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
{
            "key": "j",
            "name": "C#",
            "type": "command",
            "command": ["workbench.action.terminal.sendSequence"],
            "args": ["dotnet", "run"]
},
```

</p>
</details>

**Comment by stevenguh** [comment]
The [sendSequence](https://code.visualstudio.com/docs/terminal/advanced#_custom-sequence-keybindings) expect an object with the `text` field like you had in the shortcuts.

Try the following setting.
```
{
            "key": "j",
            "name": "C#",
            "type": "command",
            "command": "workbench.action.terminal.sendSequence",
            "args": {"text": "dotnet run"}
},
```

I am closing this now. Free feel to reopen if it doesn't solve your issue.
