### ISSUE TITLE
`<Leader>` key doesn't work

### ISSUE THREAD

**Issue by Jrol123** [VSpaceCode/vscode-which-key#92]
**Version of NVim**
```
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
``` 

**Packet manager**
Lazy Vim

**Config**
```Lua
{
        "folke/which-key.nvim",
        event = "VeryLazy",
        init = function()
          vim.o.timeout = true
          vim.o.timeoutlen = 300
        end,
        opts = {
            -- your configuration comes here
            -- or leave it empty to use the default settings
            -- refer to the configuration section below
        }
    },
```

**Checkhealth**
![изображение](https://github.com/VSpaceCode/vscode-which-key/assets/47931983/2cdc0ced-690e-4e71-ab57-8ba957290b99)

**OS**
Fedora 40

**Problem**
While other keys, (like `z`),  work fine, the `<leader>` key (`space`) doesn't work at all!

I'm new to NVim, so, maybe, i haven't configured some key at the NVim config (haven't touched it, only worked with lazy), but i don't really know what's the issue here.

Please help!

**Comment by MarcoIeni** [comment]
This is a vscode extension. Are you sure you are in the right repository?

**Comment by Jrol123** [comment]
> This is a vscode extension. Are you sure you are in the right repository?

Oh, sorry!
